redis:
  image: redis:latest
  container_name: cache
  expose:
    - 6379
app:
  build: ./
  volumes:
    - ./:/var/www/app
  links:
    - redis
  ports:
    - 3000:3000
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=3000
  command:
    sh -c 'npm i && node ./bin/www'
test:
  build: ./
  volumes:
    - ./:/var/www/app
  links:
    - redis
    - app
  environment:
    - REDIS_URL=redis://cache
  command:
    sh -c 'npm test'
